### ISSUE TITLE
verison of R?

### ISSUE THREAD

**Issue by mooreann** [hakyimlab/brainxcan#5]
Hi! What version of R did you guys use to write the snakemake scripts? I keep getting weird dependency issues for packages that don't seem to install on some versions of R (ie rgeos, rgdal) when I run the snakemake script. Thanks!

**Comment by shafiqnoa** [comment]
hi @mooreann did you solve it. I am having similar issue. it would be great if you can share your solution.

**Comment by mooreann** [comment]
Yes! I was able to 
1. install terra via mamba install -c conda-forge r-terra, which allowed me to then 
2. >install.packages("raster") in R
3. rgeos has been archived, but was able to install it manually in R via 
> packageurl <- "https://cran.r-project.org/src/contrib/Archive/rgeos/rgeos_0.6-4.tar.gz"
>install.packages(packageurl, repos=NULL, type="source")

**Comment by shafiqnoa** [comment]
Thank you very much for your reply. I am still encountering an error with rgeos. May I ask which version of R you used for this?
